AllCops:
  Exclude:
    - 'bin/**/*'
    - "grantinee.gemspec"

Security/Eval:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 100
