# MySQL
engine:    mysql
username:  root
password:  mysql
hostname:  localhost
port:      3306
database:  grantinee_development

invalid_param: blabla

# # Postgresql
# engine: postgresql
# username: postgres
# password: postgres
# hostname: localhost
# port: 5432
# database: grantinee_development
